[package]
name = "tiny_http_web"
version = "0.1.0"
authors = ["Andrea Manzini <ilmanzo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny_http = "0.6"